### ISSUE TITLE
Misleading response codes on redirects

### ISSUE THREAD

**Issue by MarkMurdock** [cyberisltd/VHOSTChecker#1]
By default LWP will follow HTTP redirects, which can lead to a response code in the vhostchecker.pl output that does not match the 3xx redirect code.  That may be desirable for some, but was giving me a lot of false 500 response codes.  I modified the LWP::Useragent creation to:

```
            $ua = LWP::UserAgent->new(
                    agent => $useragent,
                    requests_redirectable => []
            );
```

and now I am properly logging 3xx codes for vhosts that redirect.

**Comment by nopslider** [comment]
Fixed
